services:
  - type: web
    name: student-portal-postgresql
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python force_postgresql.py
    startCommand: python create_admin_simple.py && python force_postgresql.py && gunicorn std_portal.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: std_portal.settings
      - key: SECRET_KEY
        value: postgresql-production-secret-key-2025-ultimate-solution
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "student-portal-if4i.onrender.com,test-hvdl.onrender.com,localhost,127.0.0.1,0.0.0.0,*"
      - key: DATABASE_URL
        value: "postgresql://student_portal_db_a2e2_user:xP59H1q1uG9d3xwjTxMBRc90fhE86HOd@dpg-d380kkodl3ps73au33vg-a.oregon-postgres.render.com/student_portal_db_a2e2"
      - key: EMAIL_HOST_USER
        value: your-email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your-app-password
      - key: SITE_DOMAIN
        value: test-hvdl.onrender.com
      - key: SITE_NAME
        value: Sikshya Kendra

# PostgreSQL Production Configuration
# Using PostgreSQL database for production deployment