services:
  - type: web
    name: student-portal-nuclear-fix
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python force_create_admin.py
    startCommand: python create_admin_manual.py && gunicorn std_portal.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: std_portal.settings
      - key: SECRET_KEY
        value: nuclear-fix-secret-key-2025-ultimate-solution-working
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "student-portal-if4i.onrender.com,localhost,127.0.0.1,0.0.0.0,*"
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: FORCE_SQLITE
        value: "TRUE"
      - key: NUCLEAR_FIX
        value: "TRUE"
      - key: EMAIL_HOST_USER
        value: your-email@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: your-app-password
      - key: SITE_DOMAIN
        value: student-portal.onrender.com
      - key: SITE_NAME
        value: Sikshya Kendra

# NUCLEAR FIX - Using SQLite instead of PostgreSQL
# This will work immediately without any database connection issues