# Generated by Django 5.1.4 on 2025-09-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0016_merge_20250910_0142'),
        ('student_app', '0017_remove_mcqquestion_subject_and_more'),
    ]

    operations = [
    ]
